manifests/example/example.json
manifests/example/example@0.1.0.json

Signed-off-by: Kate Goldenring <kate.goldenring@fermyon.com>

Update example to use version that follows semver

---

README.md

Fixes a couple typos in the README.

docs(README.md): fix a couple typos

---

.github/workflows/schema-check.yaml

fix: fix indentation error in gh action

---

.github/workflows/schema-check.yaml

Signed-off-by: Kate Goldenring <kate.goldenring@fermyon.com>

fix: ensure schema check workflow runs on changes to manifests

---

manifests/js2wasm/js2wasm.json

Add js2wasm plugin

---

manifests/js2wasm/js2wasm.json
manifests/js2wasm/js2wasm@0.1.0.json

js2wasmv0.2.0 with linux ARM support

---

manifests/js2wasm/js2wasm.json
manifests/js2wasm/js2wasm@0.2.0.json

js2wasm: release_v0.3.0

---

manifests/js2wasm/js2wasm.json
manifests/js2wasm/js2wasm@0.2.0.json

js2wasm: fix manifest compat versions

---

manifests/check-for-update/check-for-update.json
manifests/check-for-update/check-for-update@0.0.1.json

This PR adds `check-for-update` in v0.1.0

Add check-for-update v0.1.0

---

manifests/cloud/cloud.json
manifests/cloud/cloud@0.1.2.json

Ref https://github.com/fermyon/cloud-plugin/releases/tag/v0.2.0

chore(manifests): add cloud 0.2.0

---

manifests/cloud/cloud.json
manifests/cloud/cloud@0.3.0.json

Ref https://github.com/fermyon/cloud-plugin/releases/tag/v0.4.0

chore(manifests): add cloud 0.4.0

---

manifests/cloud/cloud.json
manifests/cloud/cloud@0.6.1.json

Add cloud plugin v0.7.0

---

manifests/kube/kube.json

Add Spin kube plugin to the plugins index.

add spin kube plugin

---

manifests/kube/kube.json
manifests/kube/kube@0.0.1.json

closes https://github.com/spinkube/spin-plugin-kube/issues/43

bump to kube v0.1.0

---

manifests/cloud/cloud.json
manifests/cloud/cloud@0.8.0.json

Add [Cloud Plugin v0.9.0](https://github.com/fermyon/cloud-plugin/releases/tag/v0.9.0)

chore(manifests): add cloud 0.9.0

---

manifests/cloud/cloud.json
manifests/cloud/cloud@0.9.0.json

Ref https://github.com/fermyon/cloud-plugin/releases/tag/v0.9.1

chore(manifests): add cloud v0.9.1

---

manifests/trigger-sqs/trigger-sqs.json

Add an entry for the latest version of the [SQS trigger plugin](https://github.com/fermyon/spin-trigger-sqs).

feat(manifests): add sqs trigger plugin

---

manifests/trigger-kinesis/trigger-kinesis.json

Adds experimental Spin trigger for AWS Kinesis

add trigger-kinesis

---

manifests/trigger-kinesis/trigger-kinesis.json
manifests/trigger-kinesis/trigger-kinesis@0.1.0.json

Signed-off-by: Darwin Boersma <darwin@sprout.org>

Update trigger-kinesis to 0.2 version

---

manifests/trigger-kinesis/trigger-kinesis.json
manifests/trigger-kinesis/trigger-kinesis@0.2.0.json

Hi folks! Creating this PR to update the Kinesis trigger to the latest stable version. Thanks for your time :)

Update kinesis trigger to 0.3.1 stable version

---

manifests/pluginify/pluginify.json
manifests/pluginify/pluginify@0.7.0.json

Fully equipped with "I want it NOW" mode

Pluginify 0.8

---

manifests/trigger-command/trigger-command.json
manifests/trigger-command/trigger-command@0.2.0.json
manifests/trigger-mqtt/trigger-mqtt.json
manifests/trigger-mqtt/trigger-mqtt@0.3.0.json
manifests/trigger-sqs/trigger-sqs.json
manifests/trigger-sqs/trigger-sqs@0.8.0.json

Release the `sqs`, `mqtt`, and `command` trigger plugins

Release trigger plugins

---

manifests/azure/azure.json

Signed-off-by: Jiaxiao (mossaka) Zhou <duibao55328@gmail.com>

add spin-azure plugin to the manifest

---

manifests/azure/azure.json
manifests/azure/azure@0.0.3.json

Signed-off-by: Jiaxiao (mossaka) Zhou <duibao55328@gmail.com>

azure: release v0.0.4

---

manifests/azure/azure.json
manifests/azure/azure@0.0.4.json

Signed-off-by: Jiaxiao (mossaka) Zhou <duibao55328@gmail.com>

release azure v0.1.0
